### ISSUE TITLE
Spelling error on Electric Vehicle Speedometer

### ISSUE THREAD

**Issue by CrystalKnote** [Hebei-Studios/Tang-County-Issues#12]
### Description

This issue only affects vehicle which are *ELECTRIC VEHICLES*
These vehicles have a dedicated speedometer just because they're electric and when you switch transmission modes, you'll see "Manual" is misspelled. Please fix it!

To reproduce this- 
1. Go to Dealership and purchase any electric vehicle
2. Click on your vehicle inventory 
3. Scroll down till you find your car and click on it
4. Start your vehicle and then press the "M" key till you find the word "Manaul" 
 ~OR~
 1. Click on the Teams/Jobs Icon
 2. Scroll down and click on "Ole Online Taxi Sharing" highlighted in green
 3. Then Click on the icon labelled as Job Vehicles
 4. Click on the Car in the GUI. It is the 2019 Ora IQ Ole Taxi Sharing
 5. Start your vehicle and then press the "M" key till you find the word "Manaul" 

<img width="354" alt="Screenshot 2024-06-08 at 4 57 45 PM" src="https://github.com/Hebei-Studios/Tang-County-Issues/assets/68543635/24ae7599-7930-4259-b467-8bc96a700674">
<img width="536" alt="Screenshot 2024-06-08 at 5 06 38 PM" src="https://github.com/Hebei-Studios/Tang-County-Issues/assets/68543635/0fce9032-dd0f-48ec-9883-e035c1940b96">

### Reproduction Steps

1. Go to ...
2. Click on ...
3. Scroll down to ...

### Checklist

- [x] Reproduced the issue at least once.
- [ ] Attached valid error logs.
- [x] Included screenshots of the bug happening.

**Comment by SolarFolix** [comment]
Fixed and those EV Vehicles cant change gear mode to semi or manual for now
