### ISSUE TITLE
Display Screen Text Dislocation #2

### ISSUE THREAD

**Issue by Gezi2011** [Hebei-Studios/Tang-County-Issues#13]
### Description

The text is misaligned and appears on the wall below.

### Reproduction Steps

1. Go to the Shu Lu Middle School and you can see it on the front.

### Screenshots & Videos

https://youtu.be/pRmqv6W1LV8

### Logs

![image](https://github.com/Hebei-Studios/Tang-County-Issues/assets/172069532/c0c615d5-922c-4214-9c27-9f39092df63b)

### Checklist

- [X] Reproduced the issue at least once.
- [ ] Attached valid error logs.
- [X] Included screenshots of the bug happening.

**Comment by iceeburr** [comment]
Duplicate of #3
