### ISSUE TITLE
Infinite decimals in money

### ISSUE THREAD

**Issue by kinggy2929** [Hebei-Studios/Tang-County-Issues#15]
### Description

After selling a car you gain infinite decimal places in your money stat. If you buy a new car, the decimals also change with it. It happens anywhere from private servers to public servers. There was no log output for the issue

### Reproduction Steps

1. Sell a car
2. Buy another car
3. Sell the car again

### Screenshots & Videos

https://github.com/Hebei-Studios/Tang-County-Issues/assets/172155244/dcba88bc-dc2f-451c-b935-3d7bdb3e4c17

![image_2024-06-08_195440423](https://github.com/Hebei-Studios/Tang-County-Issues/assets/172155244/e37e1f4c-97d9-4bb9-8efd-0f70e66c38c2)

### Logs

![image_2024-06-08_195639355](https://github.com/Hebei-Studios/Tang-County-Issues/assets/172155244/9b9c15c9-6ef4-477e-b436-64d3fd01a7c9)

### Operating System

Computer, Mobile

### Checklist

- [X] Reproduced the issue at least once.
- [X] Attached valid error logs.
- [X] Included screenshots of the bug happening.

**Comment by iceeburr** [comment]
Should be fixed in the dev place. Will monitor further and try to reproduce it again, will push to main if no further issues arise. Will put it on monitoring for a few days, if there are no reports will close as resolved 👍🏻

**Comment by iceeburr** [comment]
Pushed to main game. Hope it won't have breaking changes.
Basically added `math.round()` when selling a car. To fix for users that got their data store infected I also did rounding when the player's money value is set right after they join. Once they leave it should save with the rounded value as well.
